[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "6TfxUdqLLLUTbV5HHcQmVnziTs8oBbLzWpBCZxEXhNoD"
token-mover = "FHN366auhNhbRAVQC3tkCghQ3bQNPunKotNHJkMMYi4e"

[programs.devnet]
solana_fall_transfer_hook = "6TfxUdqLLLUTbV5HHcQmVnziTs8oBbLzWpBCZxEXhNoD"
token-mover = "FHN366auhNhbRAVQC3tkCghQ3bQNPunKotNHJkMMYi4e"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
